version: '3'

services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp
    restart: unless-stopped
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
      - ./logrotate.conf:/etc/logrotate.conf
      - ./hls:/opt/data/hls
      - ./logs:/opt/data/logs
